### ISSUE TITLE
How to run it on Linux?

### ISSUE THREAD

**Issue by good-repo** [Zseni051/AutoSend#4]
Is it possible to run this script on Linux?

**Comment by Zseni051** [comment]
Haven't tried, but its safe to say NO.
You can always just use the split version, No matter what device you have as long as you have a browser you can use it.

**Comment by M2l2koPOWER** [comment]
> Is it possible to run this script on Linux?

Yes, but you can't do it in the background (if you use vps for example). Even with `nohup` it's unlikely to work since you still need to press the Y button to run the script.
