### ISSUE TITLE
Can u explain what to do in setting.json

### ISSUE THREAD

**Issue by gsweeh** [Zseni051/AutoSend#6]
I pasted channel id in setting. json when i testing it command it gos like this
![Screenshot_2022-01-27-12-53-18-008_com realvnc viewer android](https://user-images.githubusercontent.com/65717972/151311137-446908d9-8387-4a47-ba9d-2919f25c1266.jpg)
![Screenshot_2022-01-27-12-56-57-641_com realvnc viewer android](https://user-images.githubusercontent.com/65717972/151311266-97455c2e-9483-4f61-a5ae-c39f931c333f.jpg)

**Comment by Zseni051** [comment]
What do you want it to send?

**Comment by gsweeh** [comment]
> What do you want it to send? what do you want it to do?

Bro thx now. i know how to do. yours repo is usefull to me😍😍
